name: cmip6-examples
channels:
  - chrisroadmap
  - conda-forge
  - defaults
dependencies:
  - climateforcing
  - jupyter
  - nbstripout
  - iris
  - iris-sample-data
  - matplotlib
  - numpy
  - pandas
  - tqdm
  - statsmodels
  - openscm-units
  - patsy
  - scmdata
  - netcdf-scm
  - xarray
  - gcsfs
  - zarr
  - seaborn
  - nc-time-axis
